# Generated by Django 4.2.27 on 2026-01-15 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JwtTokenAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JWT Token',
                'verbose_name_plural': 'JWT Tokens',
            },
        ),
    ]
