# Generated by Django 4.2.27 on 2026-01-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_jwttokenadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
