# Generated by Django 6.0 on 2026-01-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_jwt_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwttokenadmin',
            name='expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jwttokenadmin',
            name='token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
