# Generated by Django 6.0 on 2026-01-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_jwttokenadmin_add_token_expira'),
        ('users', '0008_jwttokenadmin_expira_em_jwttokenadmin_token'),
    ]

    operations = [
    ]
