# Generated by Django 4.2.27 on 2025-12-31 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suíte',
            new_name='Suite',
        ),
    ]
