# Generated by Django 4.2.27 on 2025-12-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0002_rename_suíte_suite'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='suites',
            field=models.ManyToManyField(blank=True, related_name='rotas', to='viagens.suite'),
        ),
    ]
