# Generated by Django 4.2.27 on 2025-12-31 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viagens', '0003_rota_suites'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='capacidade_diaria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rota',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suite',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
