# Generated by Django 4.2.27 on 2025-12-31 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viagens', '0004_rota_capacidade_diaria_rota_usuario_suite_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='distancia_km',
        ),
        migrations.AlterField(
            model_name='rota',
            name='usuario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to=settings.AUTH_USER_MODEL),
        ),
    ]
