# Generated by Django 4.2.27 on 2025-12-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0005_remove_rota_distancia_km_alter_rota_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
