# Generated by Django 4.2.27 on 2025-12-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0006_rota_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='horario_partida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
