# Generated by Django 4.2.27 on 2025-12-31 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_client_user_client'),
        ('viagens', '0007_rota_horario_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='users.client'),
        ),
    ]
