# Generated by Django 4.2.27 on 2026-01-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client_name'),
        ('viagens', '0009_custumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suite',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='suite',
            name='usuario',
        ),
        migrations.AddField(
            model_name='suite',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suites', to='users.client'),
        ),
        migrations.AddField(
            model_name='suite',
            name='passageiros_inclusos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suite',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
