# Generated by Django 4.2.27 on 2026-01-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0010_remove_suite_localizacao_remove_suite_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageirosReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('cobranca_asaas_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cobranca_asaas_link', models.URLField(blank=True, null=True)),
                ('data_reserva', models.DateField(auto_now_add=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='viagens.custumer')),
                ('passageiros', models.ManyToManyField(blank=True, related_name='reservas', to='viagens.passageirosreserva')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='viagens.rota')),
                ('suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='viagens.suite')),
            ],
        ),
    ]
