# Generated by Django 4.2.27 on 2026-01-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client_name'),
        ('viagens', '0012_customer_alter_reserva_customer_delete_custumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('cpf_cnpj', 'client')},
        ),
    ]
