# Generated by Django 4.2.27 on 2026-01-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0013_alter_customer_email_alter_customer_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suite',
            name='capacidade_toneladas',
        ),
    ]
