# Generated by Django 4.2.27 on 2026-01-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0014_remove_suite_capacidade_toneladas'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='horario_chegada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
