# Generated by Django 4.2.27 on 2026-01-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0015_rota_horario_chegada'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageirosreserva',
            name='pcd',
            field=models.BooleanField(default=False),
        ),
    ]
