# Generated by Django 4.2.27 on 2026-01-13 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client_name'),
        ('viagens', '0016_passageirosreserva_pcd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto_crianca_0_4', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('desconto_crianca_5_7', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('desconto_crianca_8_10', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('desconto_acima_11', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('desconto_idoso', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('desconto_pcd', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_viagem', to='users.client')),
            ],
        ),
    ]
