# Generated by Django 4.2.27 on 2026-01-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0017_configviagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='configviagem',
            name='token_asaas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
