# Generated by Django 4.2.27 on 2026-01-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0018_configviagem_token_asaas'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageirosreserva',
            name='suite_inclusa',
            field=models.BooleanField(default=False),
        ),
    ]
