# Generated by Django 4.2.27 on 2026-01-13 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0019_passageirosreserva_suite_inclusa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passageirosreserva',
            name='suite_inclusa',
        ),
        migrations.AddField(
            model_name='passageirosreserva',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passageiros', to='viagens.suite'),
        ),
    ]
