# Generated by Django 4.2.27 on 2026-01-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0020_remove_passageirosreserva_suite_inclusa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='code_pix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='qr_code_pix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
