# Generated by Django 4.2.27 on 2026-01-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0021_reserva_code_pix_reserva_qr_code_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='status_reserva',
            field=models.CharField(choices=[('RESERVADA', 'Reservada'), ('CONFIRMADA', 'Confirmada'), ('UTILIZADA', 'Utilizada'), ('CANCELADA', 'Cancelada'), ('REEMBOLSADA', 'Reembolsada')], default='RESERVADA', max_length=20),
        ),
    ]
