# Generated by Django 4.2.27 on 2026-01-15 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0022_reserva_status_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='suites',
        ),
    ]
