# Generated by Django 6.0 on 2026-01-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0023_remove_rota_suites'),
    ]

    operations = [
        migrations.AddField(
            model_name='configviagem',
            name='link_webhook_scale4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
