# Generated by Django 6.0 on 2026-01-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0024_configviagem_link_webhook_scale4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configviagem',
            name='link_webhook_scale4',
        ),
        migrations.AddField(
            model_name='configviagem',
            name='token_scale4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
