# Generated by Django 6.0 on 2026-01-15 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0024_reserva_embarque_uuid'),
        ('viagens', '0025_remove_configviagem_link_webhook_scale4_and_more'),
    ]

    operations = [
    ]
