# Generated by Django 6.0 on 2026-01-16 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0025_reserva_status_flow'),
        ('viagens', '0026_merge_20260115_2045'),
    ]

    operations = [
    ]
